//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist..
        /// </summary>
        internal static string AccountDoesNotExist {
            get {
                return ResourceManager.GetString("AccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account can&apos;t be closed because it has funds..
        /// </summary>
        internal static string AccountHasFunds {
            get {
                return ResourceManager.GetString("AccountHasFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has not enough funds..
        /// </summary>
        internal static string AccountHasNotEnoughFunds {
            get {
                return ResourceManager.GetString("AccountHasNotEnoughFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has not enough funds..
        /// </summary>
        internal static string AccountHasNotEnoughFunds1 {
            get {
                return ResourceManager.GetString("AccountHasNotEnoughFunds1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId cannot be empty..
        /// </summary>
        internal static string AccountIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("AccountIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be positive..
        /// </summary>
        internal static string AmountIsNegative {
            get {
                return ResourceManager.GetString("AmountIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditId cannot be empty..
        /// </summary>
        internal static string CreditIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("CreditIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer already exists..
        /// </summary>
        internal static string CustomerAlreadyExists {
            get {
                return ResourceManager.GetString("CustomerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not exist..
        /// </summary>
        internal static string CustomerDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerId cannot be empty..
        /// </summary>
        internal static string CustomerIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("CustomerIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerId is required..
        /// </summary>
        internal static string CustomerIdRequired {
            get {
                return ResourceManager.GetString("CustomerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebitId cannot be empty..
        /// </summary>
        internal static string DebitIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("DebitIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is null..
        /// </summary>
        internal static string InputIsNull {
            get {
                return ResourceManager.GetString("InputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not valid..
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN must be valid..
        /// </summary>
        internal static string InvalidSSN {
            get {
                return ResourceManager.GetString("InvalidSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid text format. Use YYMMDDNNNN..
        /// </summary>
        internal static string InvalidTextFormat {
            get {
                return ResourceManager.GetString("InvalidTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN is required..
        /// </summary>
        internal static string SSNRequired {
            get {
                return ResourceManager.GetString("SSNRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Amount&apos; should be positive..
        /// </summary>
        internal static string TheAmountShouldBePositive {
            get {
                return ResourceManager.GetString("TheAmountShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text field is required..
        /// </summary>
        internal static string TheTextFieldIsRequired {
            get {
                return ResourceManager.GetString("TheTextFieldIsRequired", resourceCulture);
            }
        }
    }
}
